services:
    rmcgirr83.hidecopyright.listener:
        class: rmcgirr83\hidecopyright\event\listener
        arguments:
            - '@language'
            - '@template'
        tags:
            - { name: event.listener }
